// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAslAapYGOCs-tI9JalGNbki73Cs8P10',
    appId: '1:971800851112:web:4489e291156d72955c489d',
    messagingSenderId: '971800851112',
    projectId: 'sangeethalaya',
    authDomain: 'sangeethalaya.firebaseapp.com',
    storageBucket: 'sangeethalaya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOhCdXzKUAjIWh9sHjZgGokj3YPYDS8c',
    appId: '1:971800851112:android:d649c811640ce0cf5c489d',
    messagingSenderId: '971800851112',
    projectId: 'sangeethalaya',
    storageBucket: 'sangeethalaya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Q-q6IU1UkXGzfx92axK6pJnaiDi_bXI',
    appId: '1:971800851112:ios:c2fa6c394fe63e605c489d',
    messagingSenderId: '971800851112',
    projectId: 'sangeethalaya',
    storageBucket: 'sangeethalaya.firebasestorage.app',
    iosBundleId: 'com.example.sangeethalayaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Q-q6IU1UkXGzfx92axK6pJnaiDi_bXI',
    appId: '1:971800851112:ios:c2fa6c394fe63e605c489d',
    messagingSenderId: '971800851112',
    projectId: 'sangeethalaya',
    storageBucket: 'sangeethalaya.firebasestorage.app',
    iosBundleId: 'com.example.sangeethalayaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOAslAapYGOCs-tI9JalGNbki73Cs8P10',
    appId: '1:971800851112:web:e5ed0376cb6b4e0c5c489d',
    messagingSenderId: '971800851112',
    projectId: 'sangeethalaya',
    authDomain: 'sangeethalaya.firebaseapp.com',
    storageBucket: 'sangeethalaya.firebasestorage.app',
  );
}
